### ISSUE TITLE
Issue with dependencies between chronicle-algorithms and chronicle-bom SNAPSHOT and non-SNAPSHOT versions

### ISSUE THREAD

**Issue by metabrain** [OpenHFT/Chronicle-Algorithms#1]
Hello,

Trying the latest version of chronicle-map (3.1.4-alpha) but having some issues with getting maven to build it. One of it's dependencies is chronicle-algorithms 1.1.0 (https://oss.sonatype.org/content/repositories/releases/net/openhft/chronicle-algorithms/1.1.0/chronicle-algorithms-1.1.0.pom) which requires chronicle-bom 1.8.11-SNAPSHOT. 

The problem here being that 1.8.11 is already released, but no chronicle-bom upwards from 1.8.7-SNAPSHOT is published in sonatype (https://oss.sonatype.org/content/repositories/snapshots/net/openhft/chronicle-bom/)

Is it normal practice to associate a SNAPSHOT with a non-snapshot release version? Or is there something I can do on my side to fix this?

Cheers,
Parreira

**Comment by RobAustin** [comment]
release builds should not rely on snapshots, sounds like it could be a build issue and we make have to re-release.

**Comment by leventov** [comment]
@metabrain on the client side, as a quick&dirty fix, you could check out https://github.com/OpenHFT/OpenHFT repo, `git reset` to the version where `chronicle-bom` version is `1.8.11-SNAPSHOT` (e. g. https://github.com/OpenHFT/OpenHFT/commit/3d38adebe696bf12aee5aa540c0877c8ad341a8f) and `mvn install` locally from `chronicle-bom/` subdir.

**Comment by metabrain** [comment]
Hey all,

Thanks for the quick fix @leventov, appreciate it. Will use it this weekend if the build is not fixed in the meantime.

Thanks for the fast reply and have a nice weekend.

Cheers,
Parreira
