### ISSUE TITLE
Algorithms cannot depend on Chronicle Maps as this is circular dependancy

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Algorithms#10]
cc @BenCotton

**Comment by hft-team-city** [comment]
Released in [Chronicle-Algorithms-2.20.40](https://github.com/OpenHFT/Chronicle-Algorithms/releases/chronicle-algorithms-2.20.40), [BOM-2.20.60](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.60)
