### ISSUE TITLE
Release 2.22.2 missing on Maven central

### ISSUE THREAD

**Issue by rroesch1** [OpenHFT/Chronicle-Algorithms#13]
`net.openhft:chronicle-algorithms:jar:2.22.2` is not available on Maven central, but [chronicle-map:3.22.7](https://github.com/OpenHFT/Chronicle-Map/releases/tag/chronicle-map-3.22.7) depends on this artifact.
See: https://repo1.maven.org/maven2/net/openhft/chronicle-algorithms/2.22.2  (HTTP 404)

**Comment by glukos** [comment]
@rroesch1 Hi!
There were issues during release of chronicle-bom 2.22.126.
Please use chronicle-bom 2.22.127, it refers to https://repo1.maven.org/maven2/net/openhft/chronicle-algorithms/2.22.3/
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.openhft</groupId>
                <artifactId>chronicle-bom</artifactId>
                <version>2.22.127</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by minborg** [comment]
I am closing this issue now as a work-around has been provided. Please re-open if appropriate.
