### ISSUE TITLE
Java 11 Runtime Support

### ISSUE THREAD

**Issue by epickrram** [OpenHFT/Chronicle-Algorithms#5]
Meta-issue for tracking work related to Java 9 compatibility

**Comment by hft-team-city** [comment]
Released in Chronicle-Algorithms-1.16.0 (https://github.com/OpenHFT/Chronicle-Algorithms/releases/chronicle-algorithms-1.16.0), BOM-1.16.201 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.201)
